from subprocess import call
import sys, os, consts

def generateModelField(key, properties):
    """Takes a single field's properties and maps it to a a django object
    the key is the variable name"""

    field = ""
    try:
        field += "    %s = models.%s(" % (key, properties["type"])
    except KeyError:
        return  ""

    try:
        required = "blank=True,null=True"
        argstring = properties["argstring"]
        if len(argstring) > 0:
            argstring += ","+required
        else:
            argstring = required
        field += "%s)" % argstring

    except KeyError:
        field += ")"

    
    return field + "\n"

def generateModel(path,app,model,properties):
    """generates a specific model"""
    name = model
    print "Generating Model: " + name
    modelStr = "class %s(models.Model):\n" % name

    #process fields
    try:
        for key in iter(properties["fields"]):
            modelStr += generateModelField(key,properties["fields"][key])
    except KeyError:
        modelStr += "    pass"

    #register it in the admin panel right before returning it
    with open(os.path.join(path, 'admin.py'), 'a') as f:
        f.write("\nfrom models import %s\nadmin.site.register(%s)\n" % (name,name))

    #write the unicode function for display if nessisary
    try:
        tokens = properties["display"] + ' '
        state = 0 #0 normal 1 keyword
        buf = ''
        newString = ""
        variables = []
        for symbol in tokens:
            if state == 0:
                if symbol == '%':
                    state = 1
                else:
                    newString += symbol
            else:
                if symbol == '%':
                    newString += '%'
                    state = 0
                else:
                    if symbol == ' ':
                        state = 0
                        variables.append(buf)
                        buf = ''
                        newString += '%s '
                    else:
                        buf += symbol
        mapping = ""
        first = True
        for var in variables:
            if first:
                first = False
            else:
                mapping += ','
            mapping += 'self.'+var
        modelStr += "\n    def __unicode__(self):\n        return u'%s' %% (%s)" % (newString, mapping)


    except KeyError:
        pass #no special instructions for rendering
    
    return modelStr + "\n"
    
def generateModels(path,app,properties):
    """Generates models for a given app"""

    print "Generating models for app: " + app
    models = "from django.db import models\n\n"

    for model in iter(properties):
        models += generateModel(path, app, model, properties[model])
        
    #write the model
    with open(os.path.join(path,'models.py'), 'w') as f:
        f.write(models)

def writeModelTemplate(path,model,properties):
    """Generates the template file for the specified model"""
    
    #single object template
    t = "<div>"
    for field in iter(properties["fields"]):
        t += "\n{{ obj.%s }}" % (field)

    t += "\n</div>"
    print "writing", os.path.join(path,'templates',model+'.html')
    with open(os.path.join(path,'templates',model+'.html'), 'w') as f:
        f.write(t)


    #multiple object template
    t = "<div>\n<ul>\n"
    t += "{% for o in objs %}\n"
    try:
        t += "    <li>"+properties['listing']+"</li>\n"
    except KeyError:
        t += "    <li>{{ o.pk }}</li>\n"
    t += "{% endfor %}\n</ul>\n</div>\n"
    with open(os.path.join(path,'templates',model+"List.html"), 'w') as f:
        f.write(t)
    
def writeModelView(path,model,properties):
    """Write a view for the template generated by the above function"""

    view = "\nfrom models import %s\n" % model

    view += "\ndef %s(request,args):\n" % model
    view += "    return render(request,'%s.html',{'obj' : %s.objects.get(**args)})\n" % (model, model)

    view += "\ndef %sList(request,args):\n" % model
    view += "    return render(request,'%sList.html',{'objs' : %s.objects.filter(**args)})\n" % (model,model)

    with open(os.path.join(path,'views.py'), 'a') as f:
        f.write(view)
    
def generateModelView(path,app,properties):
    """Generate template and view for this model"""
    print "Generate templates and views"
    #generate the single item view/template
    for model in iter(properties):
        writeModelTemplate(path,model,properties[model])
        writeModelView(path,model,properties[model])

    #generate the multi item view/template
    for model in iter(properties):
        writeModelTemplate


def configureApp(path, app, properties):
    """After it has been created it is populated"""
    print "Configuring app: " + app

    #template chain to copy
    templates = os.path.join(path, 'templates')
    print "Generating: " + templates
    try:
        call(["mkdir", templates])
        call(["cp", "-a", "../../resources/templatechains/"+properties["templatechain"]+"/.", templates])
    except:
        print "Failed to generate templates"

    #generate themes
    theme = path + "/static/"
    print "Generating: " + theme
    try:
        call(["mkdir",theme])
        call(["cp","-a","../../resources/themes/"+properties["theme"]+"/.", theme])
    except:
        print "Failed to generate theme"
    
    #generate the models
    try:
        generateModels(path,app,properties["models"])

        #when done writing models for this app migrate it
        #call([consts.PYTHON, consts.MANAGE, "schemamigration", app, "--intial"])

        #generate default html for displaying the models, these are not fullon pages rather
        #they are small snipets that can be loaded by other pages by using a view to access them
        generateModelView(path,app,properties["models"])

        
    except KeyError:
        print app + " has no models"
        
def createApps(properties):
    """Generates all the apps required by the project"""

    name = properties["website"]["name"]
    consts.PYTHON = os.path.join(consts.ENV, 'bin', 'python')
    consts.PROJECT = os.path.join(consts.PATH, name)
    consts.MANAGE = os.path.join(consts.PROJECT, "manage.py")


    #create main app
    try:
        properties["apps"]
    except KeyError:
        properties["apps"] = {}

    properties["apps"]["main"] = { "templatechain" : "default", 
                                   "theme" : "default" }

    #create apps and configure them after creation
    try:
        for app in iter(properties["apps"]):
            call([consts.PYTHON, consts.MANAGE, "startapp", app])
            call(["mv", os.path.join(consts.PATH, app), consts.PROJECT])
            configureApp(os.path.join(consts.PROJECT, app), app, properties["apps"][app])

    except KeyError:
        print "No apps detected"
